services:
  py311-onbuild:
    image: srittau/cron:3.11-onbuild
    build:
      context: .
      dockerfile: Dockerfile-onbuild
      args:
        - pyversion=3.11

  py310-onbuild:
    image: srittau/cron:3.10-onbuild
    build:
      context: .
      dockerfile: Dockerfile-onbuild
      args:
        - pyversion=3.10

  py39-onbuild:
    image: srittau/cron:3.9-onbuild
    build:
      context: .
      dockerfile: Dockerfile-onbuild
      args:
        - pyversion=3.9

  latest-onbuild:
    image: srittau/cron:latest-onbuild
    build:
      context: .
      dockerfile: Dockerfile-onbuild
      args:
        - pyversion=3.11

  latest:
    image: srittau/cron:latest
    build:
      context: .
      dockerfile: Dockerfile-onbuild
      args:
        - pyversion=3.11

  py311-copy:
    image: srittau/cron:3.11-copy
    build:
      context: .
      dockerfile: Dockerfile-copy
      args:
        - pyversion=3.11

  py310-copy:
    image: srittau/cron:3.10-copy
    build:
      context: .
      dockerfile: Dockerfile-copy
      args:
        - pyversion=3.10

  py39-copy:
    image: srittau/cron:3.9-copy
    build:
      context: .
      dockerfile: Dockerfile-copy
      args:
        - pyversion=3.9

  latest-copy:
    image: srittau/cron:latest-copy
    build:
      context: .
      dockerfile: Dockerfile-copy
      args:
        - pyversion=3.11
