version: '3'
services:
  py311:
    image: srittau/cron:3.11
    build:
      context: .
      args:
        - pyversion=3.11
  py310:
    image: srittau/cron:3.10
    build:
      context: .
      args:
        - pyversion=3.10
  py39:
    image: srittau/cron:3.9
    build:
      context: .
      args:
        - pyversion=3.9
  latest:
    image: srittau/cron:latest
    build:
      context: .
      args:
        - pyversion=3.11
