services:
  py312-onbuild:
    image: srittau/cron:3.12-onbuild
    build:
      context: .
      dockerfile: Dockerfile-onbuild
      args:
        - pyversion=3.12

  py311-onbuild:
    image: srittau/cron:3.11-onbuild
    build:
      context: .
      dockerfile: Dockerfile-onbuild
      args:
        - pyversion=3.11

  latest-onbuild:
    image: srittau/cron:latest-onbuild
    build:
      context: .
      dockerfile: Dockerfile-onbuild
      args:
        - pyversion=3.12

  latest:
    image: srittau/cron:latest
    build:
      context: .
      dockerfile: Dockerfile-onbuild
      args:
        - pyversion=3.12

  py312-copy:
    image: srittau/cron:3.12-copy
    build:
      context: .
      dockerfile: Dockerfile-copy
      args:
        - pyversion=3.12

  py311-copy:
    image: srittau/cron:3.11-copy
    build:
      context: .
      dockerfile: Dockerfile-copy
      args:
        - pyversion=3.11

  latest-copy:
    image: srittau/cron:latest-copy
    build:
      context: .
      dockerfile: Dockerfile-copy
      args:
        - pyversion=3.12
