ARG pyversion=3.11
FROM python:${pyversion}-bullseye
ARG pyversion=3.11
ENV PYVERSION ${pyversion:-3.11}

# Install cron and msmtp
RUN apt-get update && \
    apt-get -yqq install cron msmtp && \
    apt-get clean

# Prepare virtualenv
RUN mkdir -p /app/log
RUN python -m venv /app/virtualenv
RUN /app/virtualenv/bin/pip install --upgrade pip setuptools

# Install crontab
COPY ./run-cron.sh /app/run-cron.sh
COPY ./run-module.sh /app/run-module.sh
RUN rm -r /etc/cron.hourly /etc/cron.daily /etc/cron.weekly /etc/cron.monthly

# Create empty msmtp configuration
RUN touch /root/.msmtprc

# Run cron
ENTRYPOINT ["/app/run-cron.sh"]
